name: Hameln
version: "${version}"
main: moe.minacle.minecraft.plugins.hameln.Plugin
description: Master the art of trident throwing with precision returns to your waiting hand!
authors:
  - Minacle
website: https://modrinth.com/plugin/hameln
api-version: "1.20"
folia-supported: false
